{% set version = "2.2.1" %}

package:
  name: deeplabcut
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/deeplabcut/deeplabcut-{{ version }}.tar.gz
  sha256: c02473287db26b0fb9006338f25af858a441b16fae6c52d9a32496d719375489
  patches:
    - relax_requirements.patch
    - 1577-avoid_hack_in_spawning_processes.patch
    - silence_light_mode_warning.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  # Confirm with upstream before making this entry point
  # https://github.com/DeepLabCut/DeepLabCut/pull/1547
  entry_points:
    - dlc = deeplabcut.cli:main
    - deeplabcut = deeplabcut:launch_dlc

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - filterpy >=1.4.4
    - ruamel.yaml >=0.15.0
    - imgaug >=0.4.0
    - numba >=0.54
    - matplotlib-base >=3.3
    - networkx >=2.6
    - numpy >=1.18.5
    - opencv
    - pandas >=1.0.1
    - scikit-image >=0.17,!=0.18.1
    - scikit-learn >=1.0
    - scipy >=1.4
    - statsmodels >=0.11,!=0.13.2
    - pytables >=3.7
    - tensorflow >=2.0
    - tensorpack >=0.11
    - tf_slim >=1.1.0
    - tqdm
    - pyyaml
    - pillow >=7.1

test:
  requires:
    - pip
  commands:
    # pip check won't pass because certain dependencies like
    # tensorflow and imgaug don't play nice with pip check
    - pip check || echo "pip check failed but ignoring"
  imports:
    # deeplabcut has "deep" dependencies.
    # On the CI, it fails with:
    # import: 'deeplabcut'
    # Traceback (most recent call last):
    #   File "/home/conda/staged-recipes/build_artifacts/deeplabcut-base_1634444737292/test_tmp/run_test.py", line 2, in <module>
    #     import deeplabcut
    #   File "/home/conda/staged-recipes/build_artifacts/deeplabcut-base_1634444737292/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.9/site-packages/deeplabcut/__init__.py", line 27, in <module>
    #     from deeplabcut import generate_training_dataset
    #   File "/home/conda/staged-recipes/build_artifacts/deeplabcut-base_1634444737292/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.9/site-packages/deeplabcut/generate_training_dataset/__init__.py", line 12, in <module>
    #     from deeplabcut.generate_training_dataset.trainingsetmanipulation import *
    #   File "/home/conda/staged-recipes/build_artifacts/deeplabcut-base_1634444737292/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.9/site-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py", line 23, in <module>
    #     from deeplabcut.pose_estimation_tensorflow import training
    #   File "/home/conda/staged-recipes/build_artifacts/deeplabcut-base_1634444737292/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/__init__.py", line 12, in <module>
    #     from deeplabcut.pose_estimation_tensorflow.datasets import *
    #   File "/home/conda/staged-recipes/build_artifacts/deeplabcut-base_1634444737292/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/datasets/__init__.py", line 11, in <module>
    #     from .pose_deterministic import DeterministicPoseDataset
    #   File "/home/conda/staged-recipes/build_artifacts/deeplabcut-base_1634444737292/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/datasets/pose_deterministic.py", line 19, in <module>
    #     from deeplabcut.utils.auxfun_videos import imread, imresize
    #   File "/home/conda/staged-recipes/build_artifacts/deeplabcut-base_1634444737292/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.9/site-packages/deeplabcut/utils/__init__.py", line 2, in <module>
    #     from deeplabcut.utils.auxfun_videos import *
    #   File "/home/conda/staged-recipes/build_artifacts/deeplabcut-base_1634444737292/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.9/site-packages/deeplabcut/utils/auxfun_videos.py", line 11, in <module>
    #     import cv2
    #   ImportError: dlopen: cannot load any more object with static TLS
    # This has been fixed for modern versions of libc.
    # https://github.com/pytorch/pytorch/issues/2575
    # https://sourceware.org/bugzilla/show_bug.cgi?id=17620
    # - deeplabcut
    # Make sure we can load the main dependecy, but not the actual package....
    # This is really a workaround.
    - tensorflow
  # Confirm with upstream before making this entry point
  # https://github.com/DeepLabCut/DeepLabCut/pull/1547
  # commands:
  #   - dlc --help

about:
  home: www.deeplabcut.org
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: DeepLabCut is a toolbox for markerless pose estimation of animals performing various tasks.
  dev_url: https://github.com/DeepLabCut/DeepLabCut

extra:
  recipe-maintainers:
    - hmaarrfk
